services:
  - type: web
    name: nl2sql-app
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: python app.py
    envVars:
      - key: OPENAI_API_KEY
        sync: false  # You still need to manually set this one in the Dashboard
      - fromDatabase:
          name: nl2sql_db       # Render database name
          property: database
          envVarName: DB_NAME
      - fromDatabase:
          name: nl2sql_db
          property: user
          envVarName: DB_USER
      - fromDatabase:
          name: nl2sql_db
          property: password
          envVarName: DB_PASSWORD
      - fromDatabase:
          name: nl2sql_db
          property: host
          envVarName: DB_HOST
      - fromDatabase:
          name: nl2sql_db
          property: port
          envVarName: DB_PORT
