services:
  - type: web
    name: nl2sql-shiny-app
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: shiny run --reload app.py
    envVars:
      - key: DB_NAME
        fromDatabase:
          name: nl2sql-db
          property: database
      - key: DB_USER
        fromDatabase:
          name: nl2sql-db
          property: user
      - key: DB_PASSWORD
        fromDatabase:
          name: nl2sql-db
          property: password
      - key: DB_HOST
        fromDatabase:
          name: nl2sql-db
          property: host
      - key: DB_PORT
        fromDatabase:
          name: nl2sql-db
          property: port
      - key: OPENAI_API_KEY
        sync: false  # Set this manually in the Render dashboard or .env file

databases:
  - name: nl2sql-db
    plan: free
