services:
  - type: web
    name: nl-to-sql-app
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: shiny run --reload app.py
    envVars:
      - key: OPENAI_API_KEY
        sync: false  # Set manually in Render dashboard or in .env (not in repo)
      - fromDatabase:
          name: postgres-db
          property: database
        key: DB_NAME
      - fromDatabase:
          name: postgres-db
          property: user
        key: DB_USER
      - fromDatabase:
          name: postgres-db
          property: password
        key: DB_PASSWORD
      - fromDatabase:
          name: postgres-db
          property: host
        key: DB_HOST
      - fromDatabase:
          name: postgres-db
          property: port
        key: DB_PORT

databases:
  - name: postgres-db
    plan: free
