services:
  - type: web
    name: nl2sql-app
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: shiny run --app app.py --host 0.0.0.0 --port 10000
    envVars:
      - key: OPENAI_API_KEY
        sync: false  # You'll set this manually in the Render Dashboard
      - fromDatabase:
          name: nl2sql_db
          property: database
          envVarName: DB_NAME
      - fromDatabase:
          name: nl2sql_db
          property: user
          envVarName: DB_USER
      - fromDatabase:
          name: nl2sql_db
          property: password
          envVarName: DB_PASSWORD
      - fromDatabase:
          name: nl2sql_db
          property: host
          envVarName: DB_HOST
      - fromDatabase:
          name: nl2sql_db
          property: port
          envVarName: DB_PORT

databases:
  - name: nl2sql_db
    databaseName: nl2sql_db
    user: nl2sql_db_user
